### PR TITLE
Update events U/M/US/UM: Rockruff, 2018 Legends

### PR DESCRIPTION
**Pull request by GreatWizard**
Events:
- [x] US/UM Rockruff (1624)
- [x] US/UM 2018 Legends (638/639)
- [x] U/M 2018 Legends (638/639)

I choose to use `S`, `M`, `US` and `UM` suffix when events are not the same not for each games.

The last time I wrote C code was 5 years ago... I bet the current code is broken but I hope you can help me to improve it ;)

What do you think of this PR overall?

### CODE REVIEW

**Comment by BernardoGiordano** [comment]
The idea is nice, but did you try to compile your code at least? It's full of function calls with too few parameters now. Make sure to get it to compile and test if it properly works with the new and the old event formats

**Comment by BernardoGiordano** [comment]
Also, why U/M? Shouldn't be better to have S/M for consistence?

**Comment by GreatWizard** [comment]
It was a typo sorry, it will be S/M ;)

I havn't tyr to build it yet because I'm setting up my env under Docker.

**Comment by GreatWizard** [comment]
A small update, I have setup a docker env: https://hub.docker.com/r/greatwizard/devkitarm-3ds/ 
If you are interested by using it.

**Comment by BernardoGiordano** [comment]
how is the state of this pull request? does everything work correctly now?

**Comment by GreatWizard** [comment]
It works well for Rockruff but not for the others. the new function getVariant is fully fonctionnal.

Can you review the diff ? I probabbly miss something but I can see it

**Comment by BernardoGiordano** [comment]
I'm not going to review the diff, as stated in the notice in the readme. PKSM is in the process of being rewritten and I have no interest in doing extra work in a branch that will be deprecated soon. If you want to still submit the Pull Request you're welcome, but make sure everything works correctly on your end

**Comment by BernardoGiordano** [comment]
Closing because the old way of storing event wondercards is going to be obsolete soon.

**Pull request closed without merging**
