### PR TITLE
Abilities and moves sorted alphabetically

### PR DESCRIPTION
**Pull request by Direlynx**

### CODE REVIEW

**Comment by BernardoGiordano** [comment]
Are you able to do an array with the old indexes too? Because in this way I can inject correctly the items

**Comment by BernardoGiordano** [comment]
Also, don't delete the old arrays, just rename the new ones like 'movesSorted' etc. In this way I can merge perfectly the commit with what I have in my mind

**Comment by Direlynx** [comment]
Should the indexes be in hex or decimal?

**Comment by BernardoGiordano** [comment]
Decimal

**Comment by Direlynx** [comment]
Not totally sure where these should go and its 2am so heres a pastebin of the indexes, I'm assuming that an index of 0 means no move/item
http://pastebin.com/iS0aQyQz

**Comment by Direlynx** [comment]
Shit don't use that I forgot to reorder the ??? items

**Comment by BernardoGiordano** [comment]
Np, I'll wait :)

**Comment by BernardoGiordano** [comment]
Little advice: when you'll resort indexes, don't put ""!

**Comment by Direlynx** [comment]
Do you still need the index arrays?

**Comment by BernardoGiordano** [comment]
Awesome, moves now works correctly. Items indexes seems to be broken btw, they don't work correctly in the application

**Comment by Direlynx** [comment]
Thats not surprising, I had to add the Sun/Moon items manually. What isn't working about them?

**Comment by BernardoGiordano** [comment]
They start to go mad. from the 40th, or around that. I'll try to sort them personally later

**Comment by BernardoGiordano** [comment]
Hello Direlynx, can I ask to delete your old PKSM fork from github? There were a few licensing issues, you can feel free to re-fork this from today's commit after that

**Comment by Direlynx** [comment]
Done.

**Pull request merged**
