### PR TITLE
Update handling trainer info

### LINKED ISSUE #147: Bank does not Change Current Handler (Not OT)
Using the bank does not change the current handler (not OT) to the save in which the Pokémon are being deposited. This causes legality issues.

### PR DESCRIPTION
**Pull request by Anty-Lemon**
Tested by trading a generated Beast Ball Eevee on Wonder Trade

Fixes #147

### CODE REVIEW

**Comment by BernardoGiordano** [comment]
[see this](https://github.com/BernardoGiordano/PKSM/commit/f4d0c6db873d31ef0d69316dd0ab8183ef28bc05)

setPkmn should only be used to effectively recalculate checksums and put data into the save buffer. Adding those lines into the 'purple button' function will also avoid that you include your own infos into other mons, which you have to give back, or adding them into OT-locked mons (see events), for example.

**Comment by Anty-Lemon** [comment]
Ohhh, I see. Thanks for pointing that out

Truth be told, I didn't realize that button did anything. Maybe it would be a good idea to add a notification to it?

**Comment by Anty-Lemon** [comment]
Actually, come to think, HT has nothing to do with OT. HT only indicates the trainer which currently owns the Pokemon.

That change makes it impossible to trade event Pokemon

**Comment by BernardoGiordano** [comment]
In fact I completely forgot that the function refers to the HT, I'm sorry. Commit was right, I'll revert mine back!

**Comment by BernardoGiordano** [comment]
everything fine, reverted to the original state

**Pull request merged**
